[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["sleepanda4523 <201213ljs@dsm.hs.kr>"]
description = ""
name = "studybot-1-"
version = "0.1.0"
[tool.poetry.dependencies]
python = "^3.7"
[tool.poetry.dev-dependencies]
